// Deterministic clinical safety rules — NOT generated by the AI.
//
// Why this file exists: an LLM asked to "write patient education" will
// often produce good general content but can inconsistently omit specific,
// well-established safety points (e.g. hypoglycemia recognition for a
// patient on insulin, or UTI risk counseling for someone on an SGLT2
// inhibitor). Those are exactly the kind of standard-of-care education
// points found in ADA/AHA/KDIGO guidelines that should NEVER depend on
// whether the model happens to mention them this generation.
//
// So instead of hoping the model remembers, we detect the trigger
// (a medication class, a lab value in a specific range) with plain code,
// and hand the model a REQUIRED list of points to cover. The model still
// writes the actual prose — it just can't skip these.
//
// This is a starter set covering common, high-impact classes/labs — not
// exhaustive. Treat gaps here as known limitations, not silent failures:
// anything not covered still falls back to the model's general knowledge,
// same as before this file existed.

const MED_SAFETY_RULES = [
  {
    match: /insulin|glipizide|gliclazide|glyburide|glimepiride|glibenclamide/i,
    label: "Hypoglycemia risk",
    mustInclude:
      "This medication can cause LOW blood sugar (hypoglycemia). Must explicitly cover: recognizing symptoms (shaking, sweating, confusion, rapid heartbeat, dizziness), immediate action (eat/drink 15g fast-acting sugar — e.g. juice, glucose tablets — recheck in 15 minutes), and when it's an emergency (loss of consciousness, seizure, unable to swallow — call emergency services).",
  },
  {
    match: /dapagliflozin|empagliflozin|canagliflozin|ertugliflozin/i,
    label: "SGLT2 inhibitor — genitourinary infection risk",
    mustInclude:
      "This medication (an SGLT2 inhibitor) increases risk of urinary tract infections and genital yeast infections. Must explicitly cover: prevention (drink plenty of water, urinate after intercourse, good hygiene) and symptoms to watch for (burning with urination, genital itching/discharge, fever) that warrant contacting their doctor.",
  },
  {
    match: /metformin/i,
    label: "Metformin — GI tolerance and rare lactic acidosis",
    mustInclude:
      "Take with food to reduce stomach upset, which is common when starting. Must mention the rare but serious warning sign of lactic acidosis (unusual muscle pain, trouble breathing, severe tiredness, stomach pain) as a reason to seek urgent care.",
  },
  {
    match: /lisinopril|enalapril|ramipril|captopril|benazepril/i,
    label: "ACE inhibitor — cough and angioedema",
    mustInclude:
      "May cause a persistent dry cough (not dangerous, but tell your doctor if bothersome). Must mention the rare but serious sign of angioedema (sudden swelling of face, lips, tongue, or throat, or difficulty breathing) as an emergency requiring immediate care. Avoid salt substitutes containing potassium unless the doctor approves.",
  },
  {
    match: /losartan|valsartan|irbesartan|candesartan|olmesartan/i,
    label: "ARB — angioedema and potassium",
    mustInclude:
      "Must mention the rare but serious sign of angioedema (sudden swelling of face, lips, tongue, or throat, or difficulty breathing) as an emergency requiring immediate care. Avoid salt substitutes containing potassium unless the doctor approves.",
  },
  {
    match: /spironolactone|eplerenone/i,
    label: "Potassium-sparing diuretic — hyperkalemia risk",
    mustInclude:
      "This medication can raise potassium levels too high, especially if combined with other blood pressure medications. Must mention symptoms of high potassium (muscle weakness, irregular heartbeat) and to avoid potassium supplements/salt substitutes unless the doctor says it's okay.",
  },
  {
    match: /furosemide|bumetanide|hydrochlorothiazide|indapamide|torsemide/i,
    label: "Diuretic — dehydration and electrolytes",
    mustInclude:
      "This medication increases urination. Must mention signs of dehydration or low electrolytes (dizziness, muscle cramps, extreme thirst, confusion) and to weigh themselves daily if being monitored for fluid status.",
  },
  {
    match: /warfarin/i,
    label: "Warfarin — bleeding risk and consistency",
    mustInclude:
      "Must mention signs of excess bleeding (unusual bruising, blood in urine/stool, prolonged bleeding from cuts, severe headache) as reasons to seek care. Keep vitamin K intake (leafy greens) CONSISTENT day to day rather than avoiding it — sudden changes affect how this medication works. Regular blood tests (INR) are required.",
  },
  {
    match: /apixaban|rivaroxaban|dabigatran|edoxaban/i,
    label: "Direct oral anticoagulant — bleeding risk",
    mustInclude:
      "Must mention signs of excess bleeding (unusual bruising, blood in urine/stool, prolonged bleeding from cuts, severe headache) as reasons to seek care immediately.",
  },
  {
    match: /atorvastatin|rosuvastatin|simvastatin|pravastatin/i,
    label: "Statin — muscle symptoms",
    mustInclude:
      "Must mention that unexplained muscle pain, tenderness, or weakness should be reported to their doctor, as this can (rarely) indicate a muscle-related side effect.",
  },
  {
    match: /tramadol|codeine|morphine|oxycodone|hydrocodone/i,
    label: "Opioid — sedation, constipation, dependency",
    mustInclude:
      "Must mention: may cause drowsiness (avoid driving until effects are known), commonly causes constipation (recommend fluids/fiber or a stool softener if advised), and not to increase the dose without consulting their doctor.",
  },
];

function getMedicationSafetyRules(medicationNames) {
  const matched = [];
  for (const name of medicationNames) {
    for (const rule of MED_SAFETY_RULES) {
      if (rule.match.test(name)) {
        matched.push({ medication: name, label: rule.label, mustInclude: rule.mustInclude });
      }
    }
  }
  return matched;
}

// --- Lab reference-range interpretation ---
// Deterministic classification against standard, cited guideline ranges
// (ADA for glucose/A1c, AHA/ACC for blood pressure, ATP/AHA for lipids,
// KDIGO for kidney function). This is calculated by code, not the AI —
// the AI is told the calculated interpretation, not asked to derive it.

function parseNumber(valueStr) {
  if (!valueStr) return null;
  const match = String(valueStr).match(/-?\d+(\.\d+)?/);
  return match ? parseFloat(match[0]) : null;
}

const LAB_INTERPRETERS = [
  {
    match: /hba1c|a1c|hemoglobin a1c|glycated hemoglobin/i,
    unit: "%",
    interpret: (v) => {
      if (v < 5.7) return { level: "normal", note: "Normal (ADA criteria)." };
      if (v < 6.5) return { level: "borderline", note: `Prediabetes range (5.7–6.4%, ADA criteria) — this is a meaningful finding worth flagging clearly to the patient as a chance to prevent progression to diabetes through lifestyle change, not just "watch and wait."` };
      return { level: "high", note: "In the diabetes range (≥6.5%, ADA criteria)." };
    },
  },
  {
    match: /fasting glucose|fasting blood sugar|fbs|fpg/i,
    unit: "mg/dL",
    interpret: (v) => {
      if (v < 100) return { level: "normal", note: "Normal fasting glucose (ADA criteria)." };
      if (v < 126) return { level: "borderline", note: "Prediabetes range (100–125 mg/dL fasting, ADA criteria) — worth flagging as a real opportunity for lifestyle intervention." };
      return { level: "high", note: "In the diabetes range (≥126 mg/dL fasting, ADA criteria)." };
    },
  },
  {
    match: /potassium|^k\+?$/i,
    unit: "mEq/L",
    interpret: (v) => {
      if (v < 3.5) return { level: "high", note: "LOW potassium (hypokalemia, <3.5 mEq/L) — can cause dangerous heart rhythm problems." };
      if (v <= 5.0) return { level: "normal", note: "Normal potassium." };
      if (v < 6.0) return { level: "high", note: "Elevated potassium (hyperkalemia, 5.1–5.9 mEq/L) — clinically significant, especially if on medications that raise potassium further." };
      return { level: "high", note: "SEVERELY elevated potassium (≥6.0 mEq/L) — urgent, risk of dangerous heart rhythm problems." };
    },
  },
  {
    match: /ldl/i,
    unit: "mg/dL",
    interpret: (v) => {
      if (v < 100) return { level: "normal", note: "Optimal LDL cholesterol." };
      if (v < 130) return { level: "borderline", note: "Near-optimal/above-optimal LDL (100–129 mg/dL)." };
      if (v < 160) return { level: "borderline", note: "Borderline-high LDL (130–159 mg/dL) — worth counseling on diet/lifestyle." };
      return { level: "high", note: "High LDL cholesterol (≥160 mg/dL)." };
    },
  },
  {
    match: /egfr/i,
    unit: "mL/min",
    interpret: (v) => {
      if (v >= 90) return { level: "normal", note: "Normal kidney function (KDIGO)." };
      if (v >= 60) return { level: "borderline", note: "Mildly decreased kidney function (eGFR 60–89, KDIGO) — often not yet symptomatic but worth monitoring." };
      if (v >= 30) return { level: "high", note: "Moderately decreased kidney function (eGFR 30–59, KDIGO) — clinically significant." };
      return { level: "high", note: "Severely decreased kidney function (eGFR <30, KDIGO) — significant finding." };
    },
  },
];

function interpretLabs(labs) {
  const interpretations = [];
  for (const lab of labs || []) {
    if (!lab.name || !lab.value) continue;
    const interpreter = LAB_INTERPRETERS.find((i) => i.match.test(lab.name));
    if (!interpreter) continue;
    const num = parseNumber(lab.value);
    if (num === null) continue;
    const result = interpreter.interpret(num);
    interpretations.push({ labName: lab.name, value: lab.value, ...result });
  }
  return interpretations;
}

// Blood pressure needs special handling since it's usually entered as
// "130/85" rather than a single number.
function interpretBloodPressure(labs) {
  const bpLab = (labs || []).find((l) => /blood pressure|^bp$/i.test(l.name || ""));
  if (!bpLab || !bpLab.value) return null;
  const match = String(bpLab.value).match(/(\d+)\s*\/\s*(\d+)/);
  if (!match) return null;
  const systolic = parseInt(match[1], 10);
  const diastolic = parseInt(match[2], 10);

  if (systolic >= 140 || diastolic >= 90) {
    return { level: "high", note: `Stage 2 hypertension (≥140/90, AHA/ACC criteria) — clinically significant.` };
  }
  if (systolic >= 130 || diastolic >= 80) {
    return { level: "borderline", note: `Stage 1 hypertension (130-139/80-89, AHA/ACC criteria) — real finding worth lifestyle counseling, not necessarily requiring medication alone.` };
  }
  if (systolic >= 120) {
    return { level: "borderline", note: `Elevated blood pressure (120-129/<80, AHA/ACC criteria) — an early signal worth addressing with lifestyle changes before it progresses.` };
  }
  return { level: "normal", note: "Normal blood pressure (AHA/ACC criteria)." };
}

// --- Combination risk detection ---
// This is the important part: individual medication rules and individual
// lab interpretations can each look fine in isolation while MISSING a
// dangerous interaction between them. Real clinical judgment often lives
// in the combination, not any single data point — e.g. an ACE inhibitor
// alone is fine, potassium-sparing diuretic alone is fine, mildly elevated
// potassium alone is a watch-item — but all three together is a real,
// escalating risk that deserves red-flag-level attention, not three
// separate mild mentions.
//
// Each rule below checks a COMBINATION of triggers (medication classes
// and/or lab findings together) and, if met, produces a single elevated
// finding meant for the redFlags section specifically — not just another
// bullet buried in "medications."

const ACE_INHIBITORS = /lisinopril|enalapril|ramipril|captopril|benazepril/i;
const ARBS = /losartan|valsartan|irbesartan|candesartan|olmesartan/i;
const K_SPARING_DIURETICS = /spironolactone|eplerenone/i;
const NSAIDS = /ibuprofen|naproxen|diclofenac|celecoxib|meloxicam/i;
const LOOP_THIAZIDE_DIURETICS = /furosemide|bumetanide|hydrochlorothiazide|indapamide|torsemide/i;
const SEDATING = /tramadol|codeine|morphine|oxycodone|hydrocodone|alprazolam|diazepam|lorazepam|clonazepam|zolpidem/i;
const SULFONYLUREAS_INSULIN = /insulin|glipizide|gliclazide|glyburide|glimepiride|glibenclamide/i;

function anyMatch(names, regex) {
  return names.some((n) => regex.test(n));
}

function getCombinationRisks(medicationNames, labInterpretations, bpInterpretation) {
  const names = medicationNames || [];
  const potassiumFinding = (labInterpretations || []).find((l) => /potassium/i.test(l.labName));
  const risks = [];

  const onAceOrArb = anyMatch(names, ACE_INHIBITORS) || anyMatch(names, ARBS);
  const onKSparing = anyMatch(names, K_SPARING_DIURETICS);

  // ACE-inhibitor/ARB + potassium-sparing diuretic (+ worse if potassium already elevated)
  if (onAceOrArb && onKSparing) {
    const kElevated = potassiumFinding && potassiumFinding.level === "high";
    risks.push({
      severity: kElevated ? "urgent" : "moderate",
      title: "ACE inhibitor/ARB + potassium-sparing diuretic combination",
      mustInclude: kElevated
        ? `This patient is on BOTH a medication like Lisinopril/Losartan AND Spironolactone/Eplerenone, which together significantly raise the risk of dangerously high potassium — AND their potassium is already elevated (${potassiumFinding.value}). This is an urgent combination risk, not a routine side-effect mention. Must clearly flag: symptoms of high potassium (muscle weakness, irregular heartbeat, palpitations) and that this needs prompt medical attention, in the redFlags section specifically, not buried in general medication notes.`
        : `This patient is on both an ACE inhibitor/ARB and a potassium-sparing diuretic together, which combined raise the risk of high potassium more than either alone. Must mention this combination specifically (not just each drug's risk separately) and recommend the patient have potassium levels monitored as advised by their doctor.`,
    });
  }

  // ACE/ARB + diuretic + NSAID = "triple whammy" acute kidney injury risk
  if (onAceOrArb && anyMatch(names, LOOP_THIAZIDE_DIURETICS) && anyMatch(names, NSAIDS)) {
    risks.push({
      severity: "moderate",
      title: '"Triple whammy" combination — ACE/ARB + diuretic + NSAID',
      mustInclude:
        "This patient's combination of a blood pressure medication (ACE inhibitor/ARB), a diuretic, and an NSAID pain reliever together increases risk of sudden kidney injury, especially with dehydration. Must mention avoiding NSAIDs (ibuprofen, naproxen) unless specifically approved by their doctor, and staying well hydrated.",
    });
  }

  // Multiple sedating medications together — respiratory depression risk
  const sedatingMatches = names.filter((n) => SEDATING.test(n));
  if (sedatingMatches.length >= 2) {
    risks.push({
      severity: "urgent",
      title: "Multiple sedating medications together",
      mustInclude: `This patient is on multiple sedating medications together (${sedatingMatches.join(", ")}), which combined increase risk of dangerous drowsiness or slowed breathing. Must flag in redFlags: avoid alcohol, do not drive until effects are known, and seek urgent care for extreme drowsiness, confusion, or slow/shallow breathing.`,
    });
  }

  // Insulin/sulfonylurea + reduced kidney function — higher hypoglycemia risk (drugs clear slower)
  const egfrFinding = (labInterpretations || []).find((l) => /egfr/i.test(l.labName));
  if (anyMatch(names, SULFONYLUREAS_INSULIN) && egfrFinding && egfrFinding.level !== "normal") {
    risks.push({
      severity: "moderate",
      title: "Diabetes medication + reduced kidney function",
      mustInclude: `This patient is on insulin/a sulfonylurea AND has reduced kidney function (${egfrFinding.labName}: ${egfrFinding.value}). Reduced kidney function means these medications can build up and increase hypoglycemia risk beyond the usual. Must mention checking blood sugar more frequently and being extra alert for low-blood-sugar symptoms.`,
    });
  }

  return risks;
}

module.exports = { getMedicationSafetyRules, interpretLabs, interpretBloodPressure, getCombinationRisks };
